
data:
      root_dir_path: <path-to-data-directory>
      arc_v1_data_dir_path: <path-to-arc-v1-data-directory>
      arc_v2_data_dir_path: <path-to-arc-v2-data-directory>
      arc_v1_repo_dir_path: <path-to-arc-v1-repo-directory>
      arc_v2_repo_dir_path: <path-to-arc-v2-repo-directory>


